from datetime import date
import re
class Billing:
    'Billing fields'
    def __init__(self, bill_id = None, appointment_id = None,
                 total_bill = None, bill_date = None):
        self.__bill_id = bill_id
        self.__appointment_id = appointment_id
        self.__total_bill= total_bill 
        self.__bill_date = bill_date

#---------------------------
#GETTERS AND SETTERS
#---------------------------

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    #Bill ID
    @property
    def bill_id(self):
        return self.__bill_id

    @bill_id.setter
    def bill_id(self, bill_id):
        if bill_id is not None and not isinstance(bill_id, int):
            raise ValueError("Bill ID must be an integer")
        self.__bill_id = bill_id
        
        # Note: ID must be a str as per set in mysql sequence (P00001)
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    #Appointment ID
    @property
    def appointment_id(self):
        return self.__appointment_id

    @appointment_id.setter
    def appointment_id(self, appointment_id):
        if appointment_id is not None and not isinstance(appointment_id, int):
            raise ValueError("Appointment ID must be an integer")
        self.__appointment_id = appointment_id
        
        # Note: ID must be a str as per set in mysql sequence (P00001)
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    #Total Bill
    @property
    def total_bill(self):
        return self.__total_bill

    @total_bill.setter
    def total_bill(self, total_bill):
        if total_bill is not None and not isinstance(total_bill, int):
            raise ValueError("total_bill must be an integer")
        out_patient_fee = 300
        self.__total_bill = total_bill + out_patient_fee
        
        # Note: Total Bill must be an autogenerated value, chosen based on the doctorID
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    #Bill Date
    @property
    def bill_date(self):
        return self.__bill_date

    @bill_date.setter
    def bill_date(self, bill_date):
        if bill_date and not isinstance(bill_date, date):
            raise ValueError("Bill date must be a date object")
        self.__bill_date = bill_date

        #Note: Bill Date must be an autogenerated current date
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    #override__str__
    def __str__(self):
        return f"""
        Bill ID: {self.__bill_id}
        Appointment ID: {self.__appointment_id}
        Total Bill: {self.__total_bill}
        Bill Date: {self.__bill_date}
        """